### ISSUE TITLE
Google OAuth Issue

### ISSUE THREAD

**Issue by rodehoed** [PowerDNS-Admin/PowerDNS-Admin#1445]
Hi,

Thanks for this release first! As the subject expects this one looks like https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1430 . We were using Oauth2 with 0.3 and it worked with the following settings:

![This is an image](https://gcdnb.pbrd.co/images/kEUlz2FFM7di.png?o=1)

I added the file from  https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1432 

The fields "google_oauth_metadata_url" and "google_oauth_jwks_url" are empty in the database.

But when logging in I get: "RuntimeError: Missing "jwks_uri" in metadata"

I don't know if it's a bug of by design. I made the conclusion that when I keep these variables empty the option will be ignored.

I tried to add https://accounts.google.com/.well-known/openid-configuration as value for the metadata url. And then it gives the following error:

`authlib.jose.errors.InvalidClaimError: invalid_claim: Invalid claim "iss"`

**Comment by AzorianMatt** [comment]
@rodehoed I ended up adding a Metadata URL config option for the remaining OAuth service providers. Perhaps check into [this issue](https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1430) that has been resolved by this change and see if it could be relevant for your situation as well?

**Comment by mrinc** [comment]
@rodehoed Please try manually setting the following params there:  

(set metadata url to empty)  
jwks url: `https://www.googleapis.com/oauth2/v3/certs`  

If that works, then all good, if not, try add the following as well: 
metadata url: `https://openidconnect.googleapis.com/v1/userinfo`

**Comment by rodehoed** [comment]
Hi @AzorianMatt . Thanks. I tried it now, and still having some issues.  Will have a Yak shaving session tomorrow and start from scratch.

**Comment by rodehoed** [comment]
BTW one thing I noticed when I disable Auto config (setting: google_oauth_auto_configure = False ) it still tries to use the Metadata url, as i'm getting an error:
_requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.googleapis.com/oauth2/v2/userinfo_

Stripping out (I think the if/else should match google_oauth_auto_configure = True) :
```
 #if isinstance(server_metadata_url, str) and len(server_metadata_url.strip()) > 0:
    #    authlib_params['server_metadata_url'] = server_metadata_url
    #else:
```
Get's me further; because I'm getting the account selector from Google. But after that PDNS Admins shows me:

_RuntimeError: Missing "jwks_uri" in metadata_

Tomorrow I will try to dig in further in the auto config option.

**Comment by AzorianMatt** [comment]
@rodehoed this makes sense as when I first implemented that change, the auto configure flag was really only meant to control the UI / UX of the process. I see the oversight though and that should be upgraded to follow the same flag since the value can remain in the database when disabled. I'll get a PR going for that fix.

**Comment by AzorianMatt** [comment]
@rodehoed I have posted a PR to correct this misbehavior and it will be available in the `dev` branch shortly.

**Comment by rodehoed** [comment]
Just to confirm https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1527 fixes https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1445#issuecomment-1506873384 indeed. Muchias gracias!

**Comment by AzorianMatt** [comment]
@rodehoed there is another issue the same as the final one you're reporting about the missing JWKS URI. Not sure if you have saw it, but I thought I understood the solution to be using the auto-configuration approach. Let me know if this helps.

**Comment by rodehoed** [comment]
Ok, finally got it working. The Google documentation is very confusing. But When I use the default values from PDA **with** auto config it works flawless.  So this means:

- **Scope**: openid email profile
- **API URL:** https://www.googleapis.com/oauth2/
- **Enable Google OAuth Auto-Configuration**: Enabled
- **Metadata URL:** https://accounts.google.com/.well-known/openid-configuration

The non-auto-config way is hard and I could not get it to work. Is there a usecase for it anyways?

**Comment by AzorianMatt** [comment]
@rodehoed I think the old way works fine prior to an upgrade of the `authlib` library but I'm not certain about that. Whether a use case still exists for that method or not, I can't say. This outcome is merely incidental of me adding the metadata URL settings in the first place (albeit the more appropriate approach).

**Comment by AzorianMatt** [comment]
@rodehoed you're very welcome!
